name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install packages 📦
        run: pnpm install

      - name: Build site 🚧
        run: pnpm build
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'

      - name: Deploy to GitHub Pages 💻
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
