name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Cache node_modules folder unless lockfile changes
      - name: Load cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install packages 📦
        run: pnpm install

      - name: Build site 🚧
        run: pnpm build
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'

      - name: Deploy to GitHub Pages 💻
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
