name: Test build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Cache node_modules folder unless yarn.lock changes
      - name: Load cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages 📦
        run: yarn install

      - name: Build site 🚧
        run: |
          yarn build
          echo "✅ Gridsome site was built successfully"
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
