name: Check lint & formatting

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install packages 📦
        run: pnpm install

      - name: Check lint & formatting ✨
        run: pnpm check
